name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore NuGet Packages
      run: nuget restore github/SimpleApp.csproj

    - name: Build Application
      run: msbuild github/SimpleApp.csproj /p:Configuration=Release /p:Platform="Any CPU"

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: github/bin/Release/SimpleApp.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
